name: CI

on:
  push:
    branches:
      - main
      - support/*
  pull_request:
  workflow_dispatch:

jobs:
  php:
    name: PHP
    uses: Icinga/github-actions/.github/workflows/php.yml@main
    with:
      # Add Director to `icingaweb2/modules` so that it is available when running unit tests.
      dependencies: |
        {
          "./vendor/icingaweb2/modules/director": "https://github.com/Icinga/icingaweb2-module-director.git"
        }
